services:
  postgres:
    image: postgres:17
    container_name: postgres_prueba
    networks:
      - default
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pruebaDB
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: